### ISSUE TITLE
TRANSACTIONS EPIC

### ISSUE THREAD

**Issue by yohagos** [yohagos/titan#4]
- [ ] Run Transactions
- [ ] Stop by Errors
- [ ] Add each Transactions to the DB
- [ ] Include Closing open Tables
- [ ] ..
