### ISSUE TITLE
APP SETTINGS EPIC

### ISSUE THREAD

**Issue by yohagos** [yohagos/titan#5]
- [ ] Overview of Settings
- [ ] Depending on User Role
- [ ] Add / Remove Money from the cashbox
- [ ] Set Receipt information
- [ ] ...
